from components import guards, ui_common
from components.package_hardening_schedule_ui import install_package_hardening_schedule_ui
from components.performance_diagnostics import begin_page_measurement, finish_and_render_page_diagnostics
from components.sprint1_schedule_hygiene import install_sprint1_schedule_hygiene
import components.schedule_timezone_ui as schedule_timezone_ui


begin_page_measurement("Member My Schedule")

schedule_timezone_ui.require_admin = guards.require_admin
schedule_timezone_ui.require_member = guards.require_member
schedule_timezone_ui.inject_global_styles = ui_common.inject_global_styles
schedule_timezone_ui.apply_luxe_theme = ui_common.apply_luxe_theme
schedule_timezone_ui.utility_logout_bar = ui_common.utility_logout_bar
schedule_timezone_ui.render_back_to_top = ui_common.render_back_to_top
schedule_timezone_ui.topbar = ui_common.topbar
schedule_timezone_ui.render_page_nav = ui_common.render_page_nav

install_package_hardening_schedule_ui(schedule_timezone_ui, admin_page=False)
install_sprint1_schedule_hygiene(schedule_timezone_ui)
schedule_timezone_ui.render_member_schedule_page()
finish_and_render_page_diagnostics("Member My Schedule")
