-- Package Hardening 1, 2 and 3 migration manifest.
-- Apply in numeric order:
--   package_hardening_123_01_schema_and_backfill.sql
--   package_hardening_123_02_metrics_and_cost_contract.sql
--   package_hardening_123_03_admin_write_contracts.sql
--   package_hardening_123_04_member_contract_and_usage_audit.sql
--   package_hardening_123_05_usage_dedupe_constraint.sql
--   package_hardening_123_06_function_permissions.sql
--   package_hardening_123_07_foreign_key_indexes.sql
--   package_hardening_123_08_total_formula.sql
--
-- Accepted rule preserved throughout:
-- Package inclusions are informational only and never grant, hide, block or
-- enforce access to HealthyMe modules.
